<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Meshwright.Geometry\Meshwright.Geometry.csproj" />
    <ProjectReference Include="..\..\src\Meshwright.IO\Meshwright.IO.csproj" />
    <ProjectReference Include="..\..\src\Meshwright.Core\Meshwright.Core.csproj" />
    <ProjectReference Include="..\..\src\Meshwright.Rendering\Meshwright.Rendering.csproj" />
    <ProjectReference Include="..\..\src\Meshwright.App\Meshwright.App.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia.Headless" Version="11.3.20" />
    <PackageReference Include="Avalonia.Headless.XUnit" Version="11.3.20" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.13.0" />
    <PackageReference Include="xunit" Version="2.9.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.0.2" />
  </ItemGroup>

</Project>
